src/qraz/frontend/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url, include

from rest_framework import routers

from . import (
    views,
)


router = routers.DefaultRouter()
router.register(r'synchronizations', views.SynchronizationViewSet, base_name = 'synchronization')
router.register(r'repositories', views.RepositoryViewSet, base_name = 'repository')
router.register(r'presentations', views.PresentationViewSet, base_name = 'presentation')

app_name = 'qraz'
urlpatterns = [
    url(
        r'^$',
        views.IndexView.as_view(),
        name='index'
    ),
    url(
        r'^presentations$',
        views.PresentationsView.as_view(),
        name='presentations'
    ),
    url(
        r'^repositories$',
        views.RepositoriesView.as_view(),
        name='repositories'
    ),
    url(
        r'^help$',
        views.HelpView.as_view(),
        name='help'
    ),
    url(
        r'^logout$',
        views.LogoutView.as_view(),
        name='logout'
    ),
    url(
        r'^api/',
        include(router.urls)
    ),
    url(
        r'^webhook/(?P<username>\w[\w_\-]+)/(?P<repository>[\w\-.]+)$',
        views.WebHookView.as_view(),
        name='webhook'
    ),
    url(
        r'^(?P<username>\w[\w_\-]+)/(?P<repository>\w[\w\-.]+)/(?P<presentation>\w[\w\-\._]+)/(?P<path>.*)?$',
        views.DownloadView.as_view(),
        name='download'
    )
]

src/qraz/frontend/templates/qraz/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>QRAZ</title>
    {% load staticfiles %}
    {% load compress %}
    {% compress css %}
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.css" %}" type="text/css" charset="utf-8">
    <link rel="stylesheet" href="{% static "bootswatch/sandstone/bootstrap.css" %}" type="text/css" charset="utf-8">
    <link rel="stylesheet" href="{% static "font-awesome/css/font-awesome.css" %}" type="text/css" charset="utf-8">
    <link rel="stylesheet" href="{% static "qraz/frontend.css" %}" type="text/css" charset="utf-8">
    {% endcompress %}
    {% compress js %}
    <script src="{% static "jquery/jquery.js" %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static "bootstrap/js/bootstrap.js" %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static "angular.js/angular.js" %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static "angular.js/angular-resource.js" %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static "angular.js/angular-animate.js" %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static "qraz/frontend.js" %}" type="text/javascript" charset="utf-8"></script>
    {% endcompress %}
  </head>
  <body ng-app="FrontendApp" ng-strict-di>
    {% block body %}
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'qraz:index' %}">
            <i class="fa fa-picture-o"></i>
            QRAZ
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
              <a href="{% url 'qraz:presentations' %}">
                <i class="fa fa-files-o"></i>
                Presentations
              </a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-user"></i>
                {{ user }}
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="{% url 'qraz:repositories' %}">
                    <i class="fa fa-github"></i>
                    Repositories
                  </a>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <a href="{% url 'qraz:logout' %}">
                    <i class="fa fa-sign-out"></i>
                    Logout
                  </a>
                </li>
              </ul>
            </li>
            {% else %}
            <li>
              <a href="{% url 'social:begin' 'github' %}">
                <i class="fa fa-sign-in"></i>
                Sign in with Github
              </a>
            </li>
            {% endif %}
            <li>
              <a href="{% url 'qraz:help' %}">
                <i class="fa fa-info-circle"></i>
                Help
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    {% endblock %}
  </body>
</html>

src/qraz/frontend/templates/qraz/help.html
{% extends "qraz/base.html" %}

{% block content %}
<h1>What is QRAZ?</h1>
<p>
QRAZ provides a simple integration of <a href="https://pypi.python.org/pypi/hovercraft/">Hovercraft</a> with <a href="https://github.com/">GitHub</a>.
</p>

<h1>How does it work?</h1>
<p>
You can login to QRAZ with your GitHub account and activate one or more of your repositories that contain hovercraft presentations.
</p>

<h1>How does QRAZ know what files to convert?</h1>
<p>
Once you have enabled a repository QRAZ will start monitoring it for pushes, using GitHub webhooks. To tell QRAz which file to convert with hovercraft, you need
to create a file called <code>.hovercraft.yml</code> inside your repository. This works similar to services like <a href="https://travis-ci.org/">Travis-CI</a>
and their <code>.travis.yml</code>. The content of the file needs to be valid <a href="http://yaml.org/">YAML</a>.
</p>

<p>
Here is an example for <code>.hovercraft.yml</code>:
<pre>
04-html:
  source: 04-html.rst
  css:
    - css/campus02.css
  template: default
  auto-console: false
  skip-help: true
  skip-notes: true
  assets:
    - figures
    - videos
    - images
    - examples
04-html-simple:
  source: 04-html.rst
  template: simple
</pre>
This would build two presentations named <code>04-html</code> and <code>04-html-simple</code> using the file <code>04-html.rst</code> at the root of the repository as input for hovercraft.
Each presentation in the YAML file can have several attributes, all of which are optional:
<dl>
  <dt><code>source</code></dt>
  <dd>
  The name of the input file for hovercraft relative to the repository root. If this is not specified, QRAZ will try to use a file named <code>&lt;presentation-name&gt;.rst</code>.
  </dd>
  <dt><code>css</code></dt>
  <dd>
  A list of CSS filenames that should be included in the presentation, relative to the repository root.
  </dd>
  <dt><code>template</code></dt>
  <dd>
  The hovercraft template to use. If not specified, a value of <code>default</code> is used.
  </dd>
  <dt><code>auto-console</code></dt>
  <dd>
  </dd>
  <dt><code>auto-console</code></dt>
  <dd>
  </dd>
  <dt><code>auto-console</code></dt>
  <dd>
  </dd>
  <dt><code>auto-console</code></dt>
  <dd>
  </dd>
</dl>
</dl>
</dl>
</dl>

</p>
{% endblock %}

src/qraz/frontend/templates/qraz/index.html
{% extends "qraz/base.html" %}

{% block content %}
<div class="container theme-showcase" role="main">
  <div class="jumbotron">
    <h1>Build your slides with hovercraft</h1>
    <p>QRAZ is hovercraft as a service. Create your slides using Restructured Text, push it to Github and let QRAZ build and host your slides for you.</p>
  </div>
</div>
{% endblock %}

src/qraz/frontend/templates/qraz/presentations.html
{% extends "qraz/base.html" %}

{% block content %}
<div class="container" role="main" ng-controller="PresentationsController" ng-cloak>
  <div class="page-header">
    <h1>Presentations</h1>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <form>
        <div class="form-group">
          <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-search"></i></div>
            <input type="text" class="form-control" placeholder="Filter by name" ng-model="searchName">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button" ng-click="sortType = 'name'; sortReverse = !sortReverse">
                <span ng-show="!sortReverse" class="fa fa-caret-down"></span>
                <span ng-show="sortReverse" class="fa fa-caret-up"></span>
              </button>
            </span>
          </div>
        </div>
      </form>
      <div class="list-group">
        <a href="{$ pres.url $}" class="list-group-item" ng-repeat="pres in presentations | orderBy:'fullname':sortReverse | filter:{fullname:searchName}">
          <span class="fa fa-play-circle"></span>
          {$ pres.fullname $}
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/qraz/frontend/templates/qraz/repositories.html
{% extends "qraz/base.html" %}

{% block content %}
<div ng-controller="RepositoriesController" ng-cloak>
  <div class="page-header">
    <div class='btn-toolbar pull-right'>
      <div class='btn-group'>
        <button type='button' class='btn btn-primary' ng-click="syncGithub()" ng-hide="syncActive">Sync with Github</button>
      </div>
    </div>
      <h1>Repositories</h1>
  </div>
  <div class="row" ng-show="syncActive">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">GitHub synchronization</h3>
        </div>
        <div class="panel-body">
          We are now syncing all your public Github repositories, this may take a while. Please be patient!
          <div class="progress" ng-show="sync.state == 'PROGRESS'">
            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="{$ syncProgress $}" aria-valuemin="0" aria-valuemax="100" ng-style="{width: syncProgress + '%'}">
              {$ sync.result.current $}/{$ sync.result.total $}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row" ng-hide="syncActive">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-body">
          Click on any repository to enable/disable QRAZ integration.
        </div>
      </div>
      <form>
        <div class="form-group">
          <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-search"></i></div>
            <input type="text" class="form-control" placeholder="Filter by repository name" ng-model="searchName">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button" ng-click="sortType = 'name'; sortReverse = !sortReverse">
                <span ng-show="!sortReverse" class="fa fa-caret-down"></span>
                <span ng-show="sortReverse" class="fa fa-caret-up"></span>
              </button>
            </span>
          </div>
        </div>
      </form>
      <div class="list-group">
        <a
           href="#"
           class="list-group-item"
           ng-repeat="repo in repositories | orderBy:'name':sortReverse | filter:{name:searchName}"
           ng-class="{'list-group-item-success': repo.state == 'active', 'disabled': repo._working}"
           ng-click="toggleRepository(repo)">
          <span class="fa" ng-class="{'fa-folder-open': repo.state == 'active', 'fa-folder': repo.state != 'active', 'fa-spin': repo._working}"></span>
          {$ repo.name $}
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}